project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
commit_message: '[ci skip]'
files:
  - source: /app/javascript/mastodon/locales-fedibird/en.json
    translation: /app/javascript/mastodon/locales-fedibird/%two_letters_code%.json
    update_option: update_as_unapproved
  - source: /config/locales-fedibird/en.yml
    translation: /config/locales-fedibird/%two_letters_code%.yml
    update_option: update_as_unapproved
  - source: /config/locales-fedibird/simple_form.en.yml
    translation: /config/locales-fedibird/simple_form.%two_letters_code%.yml
    update_option: update_as_unapproved
  # - source: /config/locales-fedibird/activerecord.en.yml
  #   translation: /config/locales-fedibird/activerecord.%two_letters_code%.yml
  #   update_option: update_as_unapproved
  # - source: /config/locales-fedibird/devise.en.yml
  #   translation: /config/locales-fedibird/devise.%two_letters_code%.yml
  #   update_option: update_as_unapproved
  # - source: /config/locales-fedibird/doorkeeper.en.yml
  #   translation: /config/locales-fedibird/doorkeeper.%two_letters_code%.yml
  #   update_option: update_as_unapproved
