name: Crowdin Action

on:
  push:
    branches: [ main ]
    paths:
      - 'app/javascript/mastodon/locales-fedibird/**'
      - 'config/locales-fedibird/**'
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.3.3
      with:
        upload_translations: true
        download_translations: true
        skip_untranslated_strings: true        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
